version: '3'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cod3r
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

networks:
  my-network:
    external: true